// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddqzhecccwwtcskbiver.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkcXpoZWNjY3d3dGNza2JpdmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzExMzIsImV4cCI6MjA3MjI0NzEzMn0.ifq34vzZWUj0d9Xkhhmsnt3DrjoocGgtyEvhlL0_T9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});